### ISSUE TITLE
tanya mas

### ISSUE THREAD

**Issue by armanhilmawan** [rzldin/mypos#14]
Severity: Warning

Message: require(C:\xampp\htdocs\pos3\assets\vendor\composer/../symfony/deprecation-contracts/function.php): failed to open stream: No such file or directory

Filename: composer/autoload_real.php

Line Number: 69

saat saya mau lihat terjadi kesalahan ini mas kira2 knp ya

**Comment by rzldin** [comment]
Composer nya udah di update mas?

Pada tanggal Min, 6 Jun 2021 09.30, Arman Hilmawan ***@***.***>
menulis:

**Comment by armanhilmawan** [comment]
sudah mass

**Comment by armanhilmawan** [comment]
Composer version 2.0.13 saya pake -v ini

**Comment by rzldin** [comment]
ini mas, coba langusng ekstrak dari sini, bisa ga. Soalnya, ada juga yang
kaya mas, permasalahannya. Saya bingung wkwkkw, di saya bisa bisa aja
soalnya. coba pake ini ya mas.
 mypos.zip
<https://drive.google.com/file/d/1bqXO6S-NkirVg26qxb7tUTvoXjsOATnE/view?usp=drive_web>

**Comment by armanhilmawan** [comment]
oke mas, saya sudah Request Sent

**Comment by rzldin** [comment]
Sudah saya beri izin mas

Pada tanggal Rab, 9 Jun 2021 10.29, Arman Hilmawan ***@***.***>
menulis:

**Comment by armanhilmawan** [comment]
makasih banyak mas saya coba

**Comment by benmoumene** [comment]
same problem please send me the diroctory vendor full in benmoumene ***@***gmail.com
@rzldin

**Comment by rzldin** [comment]
done sir

**Comment by andiariyandi** [comment]
@rzldin sama mas, permalsahanya, sdh request asumitudu@gmail.com terimkasih mas
