### ISSUE TITLE
izin download mas,,isue sebelumnya masih ada mas

### ISSUE THREAD

**Issue by miftahulghonikendal** [rzldin/mypos#17]
A PHP Error was encountered
Severity: Warning

Message: require(/opt/lampp/htdocs/mypos/assets/vendor/composer/../symfony/deprecation-contracts/function.php): Failed to open stream: No such file or directory

Filename: composer/autoload_real.php

Line Number: 69

Backtrace:

File: /opt/lampp/htdocs/mypos/assets/vendor/composer/autoload_real.php
Line: 69
Function: _error_handler

File: /opt/lampp/htdocs/mypos/assets/vendor/composer/autoload_real.php
Line: 69
Function: require

File: /opt/lampp/htdocs/mypos/assets/vendor/composer/autoload_real.php
Line: 59
Function: composerRequireffb9b37d104c133a5dab9f827a61bcf8

File: /opt/lampp/htdocs/mypos/assets/vendor/autoload.php
Line: 7
Function: getLoader

File: /opt/lampp/htdocs/mypos/index.php
Line: 315
Function: require_once

**Comment by rzldin** [comment]
oke sebentar ya

**Comment by miftahulghonikendal** [comment]
saya kirim permintaan akses drive ya mas...terima kasih banyak mas
