### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by swalayan-hasbuna** [rzldin/mypos#18]
![image](https://user-images.githubusercontent.com/74512439/126157553-7e03370d-ac81-43f2-b3a6-c4d7a355b4d0.png)

**Comment by swalayan-hasbuna** [comment]
minta kntaknya mas,, untuk kerjasama

**Comment by rzldin** [comment]
Bisa hubungi saya, di whatsapp 082114377944

Pada tanggal Sen, 19 Jul 2021 19.34, swalayan hasbuna <
***@***.***> menulis:
