### ISSUE TITLE
Mohon arahannya Kak, Terima kasih

### ISSUE THREAD

**Issue by royz-pakaya** [rzldin/mypos#29]
![image](https://user-images.githubusercontent.com/98468575/161088207-d2177cee-55e5-45df-be1e-52e3383bbfef.png)

**Comment by rzldin** [comment]
https://drive.google.com/file/d/1Utnjn0PdvcyfVRkW_sMPicdBlmZQcHc8/view?usp=sharing

silahkan download filenya disitu ya

**Comment by randyaryanf** [comment]
<img width="960" alt="ss error" src="https://user-images.githubusercontent.com/93695019/192683669-8827c019-fa1e-4f79-a19c-0a8c923a3598.PNG">

**Comment by randyaryanf** [comment]
sorry, error bro

**Comment by royz-pakaya** [comment]
Terima kasih

Pada tanggal Min, 3 Apr 2022 pukul 14.17 Rizal Jihadudin <
***@***.***> menulis:
