### ISSUE TITLE
error composer

### ISSUE THREAD

**Issue by azaingo** [rzldin/mypos#44]
Message: require(C:\xampp\htdocs\mypos\assets\vendor\composer/../symfony/deprecation-contracts/function.php): failed to open stream: No such file or directory

Filename: composer/autoload_real.php

**Comment by azaingo** [comment]
mohon arahannya ka..

**Comment by zidan878** [comment]
lah itu masalahnya gimana ini

**Comment by zidan878** [comment]
ini gimana solusinya ka tolong dibantu

**Comment by upin1506** [comment]
download lagi aja filenya disini
https://drive.google.com/file/d/1Utnjn0PdvcyfVRkW_sMPicdBlmZQcHc8/view?usp=sharing

**Comment by azaingo** [comment]
itu sdh fix blm ya ka....

**Comment by rzldin** [comment]
silahkan di coba kembali
